//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FikirsenWebSitesi_ASPNET_MVC.Models.entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FikirsenWebDBEntities3 : DbContext
    {
        public FikirsenWebDBEntities3()
            : base("name=FikirsenWebDBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Kullanicilar> Tbl_Kullanicilar { get; set; }
        public virtual DbSet<Tbl_Yazilar> Tbl_Yazilar { get; set; }
        public virtual DbSet<Tbl_Yorumlar> Tbl_Yorumlar { get; set; }
    }
}
