//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FikirsenWebSitesi_ASPNET_MVC.Models.entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Yazilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Yazilar()
        {
            this.Tbl_Yorumlar = new HashSet<Tbl_Yorumlar>();
        }
    
        public int YaziID { get; set; }
        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz.")]
        [StringLength(50, ErrorMessage = "En Fazla 50 Karakterlik Giriþ Yapabilirsiniz.")]
        public string YaziBaslik { get; set; }
        public string YaziIcerik { get; set; }
        public Nullable<int> YazarID { get; set; }
    
        public virtual Tbl_Kullanicilar Tbl_Kullanicilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Yorumlar> Tbl_Yorumlar { get; set; }
    }
}
