//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FikirsenWebSitesi_ASPNET_MVC.Models.entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Kullanicilar()
        {
            this.Tbl_Yazilar = new HashSet<Tbl_Yazilar>();
            this.Tbl_Yorumlar = new HashSet<Tbl_Yorumlar>();
        }
    
        public int KullaniciID { get; set; }
        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz.")]
        [StringLength(50, ErrorMessage = "En Fazla 50 Karakterlik Giriþ Yapabilirsiniz.")]
        public string KullaniciAd { get; set; }
        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz.")]
        [StringLength(50, ErrorMessage = "En Fazla 50 Karakterlik Giriþ Yapabilirsiniz.")]
        public string KullaniciSoyad { get; set; }
        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz.")]
        [StringLength(100, ErrorMessage = "En Fazla 100 Karakterlik Giriþ Yapabilirsiniz.")]
        public string KullaniciMail { get; set; }
        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz.")]
        [StringLength(50, ErrorMessage = "En Fazla 50 Karakterlik Giriþ Yapabilirsiniz.")]
        public string KullaniciGirisAd { get; set; }
        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz.")]
        [StringLength(50, ErrorMessage = "En Fazla 50 Karakterlik Giriþ Yapabilirsiniz.")]
        public string KullaniciGirisSifre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Yazilar> Tbl_Yazilar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Yorumlar> Tbl_Yorumlar { get; set; }
    }
}
