//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FikirsenWebSitesi_ASPNET_MVC.Models.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Yorumlar
    {
        public int YorumID { get; set; }
        public string YorumIcerik { get; set; }
        public Nullable<int> YorumYazari { get; set; }
        public Nullable<int> YaziID { get; set; }
    
        public virtual Tbl_Kullanicilar Tbl_Kullanicilar { get; set; }
        public virtual Tbl_Yazilar Tbl_Yazilar { get; set; }
    }
}
